### ISSUE TITLE
dummy issue

### ISSUE THREAD

**Issue by BlackCapCoder** [BlackCapCoder/pogo-problem#1]

**Comment by BlackCapCoder** [comment]
@bolric17 Hi! Wanna help me out with the [pogo problem](https://github.com/BlackCapCoder/pogo-problem/blob/master/problems/Pogo.md)? Currently my best effort is `O(L%C)`

**Comment by bolric17** [comment]
@BlackCapCoder Sure! I can probably help you out, considering my extremely high level of coding. What do you need help for?

**Comment by bolric17** [comment]
Try L0C0(M0N4Ey). Worked for me.

**Comment by BlackCapCoder** [comment]
@bolric17 `O(L (modulo C))` is the worst case run-time given in BigO notation- not code. These are math problems- not strictly programming!

**Comment by BlackCapCoder** [comment]
@bolric17 Anyways, it would help me out immensely if you could either prove or disprove that [N-SeqPiñata'](https://github.com/BlackCapCoder/pogo-problem/blob/master/problems/N-SeqPi%C3%B1ata'.md) is equivalent to [piñata](https://github.com/BlackCapCoder/pogo-problem/blob/master/problems/Pi%C3%B1ata.md).

I have reason to believe this is the case because `N-SeqPogo' = Pogo`

**Comment by bolric17** [comment]
Oh.. my bad! Seems like my skills have come too short. I have nothing to contribute to a positive evolution of your pogo problem. Looking forward to hearing from you when you have found the best solution, you Tiger Woods golf-pro!!

**Comment by BlackCapCoder** [comment]
@bolric17 As far as I am concerned we have the same mathematical background and you're just being lazy.

Let me inform you that this project - if successful - would also solve the famous [P vs NP problem](https://www.youtube.com/watch?v=YX40hbAHx3s), which is the biggest problem in all of computer science, and which has a million dollar prize attached to it. That's half a million dollar and a spot in the history books for both of us!

**Comment by BlackCapCoder** [comment]
@bolric17 Lorem. Are you at school?

**Comment by bolric17** [comment]
@BlackCapCoder Jeg kommer litt etter 11 idag. Join!

**Comment by bolric17** [comment]
Ipsum!!!!!! Come to school tomorrow, we are meeting up with the web group

**Comment by BlackCapCoder** [comment]
@bolric17 Dolor!!!! When is this?

**Comment by BlackCapCoder** [comment]
@bolric17 8PM, gotcha!

**Comment by bolric17** [comment]
Hahaha no. We have decided to meet around 11... AM.
